import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import { useRouter } from 'next/router'

// styled-components
const RedLink = styled.a`
  color: red;
`

// Prefetch: 
// - Only prefetches links appear in the viewport
// - Only enabled in production
// - Disabled in slow network, when users have save-data turned on.
// - Only fetches javascript, doesn't execute it.

const Home: NextPage = () => {

  const router = useRouter()

  function goToDetailPage() {
    router.push({
      pathname:'posts/[postId]',
      query:{
        postId: 123,
        ref: 'social'
      }
    })
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <Link href='/about'>
          <a>Go to about</a>
        </Link>
        <Link href='/about'>
          <RedLink>Go to about</RedLink>
        </Link>

        <button onClick={goToDetailPage}>Go to post detail page</button>        
      </main>

     
    </div>
  )
}

export default Home
